#!/bin/bash

ulimit -SHn 65535

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
. /lib/lsb/init-functions

NAME=uucin-python-giserver


ENV_HOME=/usr/local/uu_giserver_env
PROJECT_HOME=/usr/local/uu_giserver
PARAMS_PORT=8000
PARAMS_C=10

function start()
{
        PIDS=`ps -ef|grep "python"|grep "uu_giserver"|grep -v "grep"|awk '{print $2}'`;

        if [ -z "$PIDS" ]
        then
                source $ENV_HOME/bin/activate
		nohup python $PROJECT_HOME/manage.py run_gunicorn -c $PROJECT_HOME/gunicorn.config -b 0.0.0.0:$PARAMS_PORT > /var/log/giserver.log 2>&1 &
#                nohup python $PROJECT_HOME/run_stornado.py -b 0.0.0.0:$PARAMS_PORT -c $PARAMS_C > /var/log/giserver.log 2>&1 &
		log_success_msg "$NAME starting ok "
        else
                status
        fi
}

function stop()
{
	PIDS=`ps -ef|grep "python"|grep "uu_giserver"|grep -v "grep"|awk '{print $2}'`;
	for pid in $PIDS;
	do
	        kill -9 $pid
	done
        log_success_msg "$NAME stop ok "
}

function status()
{
        PIDS=`ps -ef|grep "python"|grep "uu_giserver"|grep -v "grep"|awk '{print $2}'`;
        if [ -z "$PIDS" ]
        then
                log_success_msg "$NAME status is stoped"
        else
                log_success_msg "$NAME status is runing"
                for pid in $PIDS;
                do
                        log_success_msg "PID is $pid"
                done
        fi
}


case "$1" in

        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                stop
                start
                ;;
        status)
                status
                ;;
        *)
            echo "Usage: $0 in start stop restart status"
            exit 1
                ;;
esac

