#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
. /lib/lsb/init-functions
NAME=uucin_lbs_kratos


init_project()
{

	wget "http://127.0.0.1:9280/kratos/address/code"  -O /dev/null -T 600 > /dev/null 2>&1

	return_code=$?

	if [ 0 -ne $return_code ]
	then
		log_failure_msg "$NAME init project failure! wget return code $return_code"
		exit $return_code
	else
		log_success_msg "init project ok"
	fi
}

start()
{
	service uucin-tomcat7-kratos start
	log_success_msg "waiting tomcat start............"
	sleep 15;
	init_project
	service uucin-nginx-kratos-conf start
	log_success_msg "$NAME start ok"
}

stop()
{
	service uucin-nginx-kratos-conf stop
        service uucin-tomcat7-kratos stop
        log_success_msg "$NAME stop ok"
}

reload()
{
	init_project
	service uucin-nginx-kratos-conf restart
}

case "$1" in
	
	start)
                start
                ;;
        stop)
                stop
                ;;
        reload)
		reload
                ;;
        restart)
		stop
		start
                ;;
        *)
            echo "Usage: $0 in start restart stop reload"
            exit 1
                ;;
esac
