#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
. /lib/lsb/init-functions
NAME=uucin_lbs_apollo


init_apollo()
{

	wget "http://127.0.0.1:9180/apollo/address/code"  -O /dev/null -T 600 > /dev/null 2>&1

	if [ 0 -ne $? ]
	then
		log_failure_msg "$NAME init apollo failure! wget return code $?"
		exit $?
	else
		log_success_msg "init apollo ok"
	fi
}

start()
{
	service uucin-tomcat7-apollo start
	log_success_msg "waiting tomcat start............"
	sleep 15;
	init_apollo
	service uucin-nginx-apollo-conf start
	service uucin-python-longlive start
	log_success_msg "$NAME start ok"
}

stop()
{
	service uucin-python-longlive stop
	service uucin-nginx-apollo-conf stop
        service uucin-tomcat7-apollo stop
        log_success_msg "$NAME stop ok"
}

reload()
{
	service uucin-nginx-apollo-conf restart
	init_apollo
}

case "$1" in
	
	start)
                start
                ;;
        stop)
                stop
                ;;
        reload)
		reload
                ;;
        restart)
		stop
		start
                ;;
        *)
            echo "Usage: $0 in start restart stop reload"
            exit 1
                ;;
esac
