#!/bin/bash

ulimit -SHn 65535

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
. /lib/lsb/init-functions
NAME=uucin_lbs_soul


start()
{
	service uucin-tomcat7-soul start
	log_success_msg "waiting tomcat start............"
	sleep 15;
	service uucin-nginx-soul-conf start
	log_success_msg "$NAME start ok"
}

stop()
{
	service uucin-nginx-soul-conf stop
        service uucin-tomcat7-soul stop
        log_success_msg "$NAME stop ok"
}

reload()
{
	service uucin-nginx-soul-conf restart
}

case "$1" in
	
	start)
                start
                ;;
        stop)
                stop
                ;;
        reload)
		reload
                ;;
        restart)
		stop
		sleep 5;
		start
                ;;
        *)
            echo "Usage: $0 in start restart stop reload"
            exit 1
                ;;
esac
