#!/bin/bash

ulimit -SHn 65535

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
. /lib/lsb/init-functions
NAME=uucin_lbs_bottle


init_bottle()
{

	log_success_msg "waiting bottle init............"

	wget "http://127.0.0.1:9080/bottle/address_code"  -O /dev/null -T 600 > /dev/null 2>&1

	log_success_msg "init bottle ok"
}

start()
{
	service uucin-tomcat7-bottle start
	log_success_msg "waiting tomcat start............"
	sleep 15;
	init_bottle
	service uucin-nginx-bottle-conf start
	log_success_msg "$NAME start ok"
}

stop()
{
	service uucin-nginx-bottle-conf stop
        service uucin-tomcat7-bottle stop
        log_success_msg "$NAME stop ok"
}

reload()
{
	service uucin-nginx-bottle-conf restart
	init_bottle
}

case "$1" in
	
	start)
                start
                ;;
        stop)
                stop
                ;;
        reload)
		reload
                ;;
        restart)
		stop
		sleep 5;
		start
                ;;
        *)
            echo "Usage: $0 in start restart stop reload"
            exit 1
                ;;
esac
